// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const REGISTER_INITIATED = 'REGISTER_INITIATED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOAD_INITIATED = 'LOAD_INITIATED';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILED = 'LOAD_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER'

// PROFILE
export const LOAD_PROFILE_INITIATED = 'LOAD_PROFILE_INITIATED'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'