// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const REGISTER_INITIATED = 'REGISTER_INITIATED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOAD_INITIATED = 'LOAD_INITIATED';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILED = 'LOAD_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER'

// PROFILE
export const LOAD_PROFILE_INITIATED = 'LOAD_PROFILE_INITIATED'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const CREATE_PROFILE_INITIATED = 'CREATE_PROFILE_INITIATED'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAILED = 'CREATE_PROFILE_FAILED'

// ACCOUNT
export const ACCOUNT_DELETE_INITIATED = 'ACCOUNT_DELETE_INITIATED'
export const ACCOUNT_DELETE_SUCCESS = 'ACCOUNT_DELETE_SUCCESS'
export const ACCOUNT_DELETE_FAILED = 'ACCOUNT_DELETE_FAILED'

// EXPERIENCES & EDUCATIONS
export const ADD_EXPERIENCE_INITIATED = 'ADD_EXPERIENCE_INITIATED'
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS'
export const ADD_EXPERIENCE_FAILED = 'ADD_EXPERIENCE_FAILED'
export const DELETE_EXPERIENCE_INITIATED = 'DELETE_EXPERIENCE_INITIATED'
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'
export const DELETE_EXPERIENCE_FAILED = 'DELETE_EXPERIENCE_FAILED'

export const ADD_EDUCATION_INITIATED = 'ADD_EDUCATION_INITIATED'
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS'
export const ADD_EDUCATION_FAILED = 'ADD_EDUCATION_FAILED'
export const DELETE_EDUCATION_INITIATED = 'DELETE_EDUCATION_INITIATED'
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS'
export const DELETE_EDUCATION_FAILED = 'DELETE_EDUCATION_FAILED'